import '../../entities/scan_candidate.dart';
import '../../entities/scan_payload.dart';
import '../../enums/scan_kind.dart';
import '../../failures/scan_parse_failure.dart';
import '../../normalization/phone_normalization.dart';
import '../scan_parse_result.dart';
import '../scan_payload_parser.dart';

/// Parses `sms:`/`smsto:` payloads, supporting both the RFC-style
/// `sms:number?body=text` query form and the common
/// `smsto:number:message` colon-separated form generated by many QR
/// tools.
class SmsParser implements ScanPayloadParser {
  const SmsParser();

  @override
  bool canParse(ScanCandidate candidate) {
    final lower = candidate.rawValue.trim().toLowerCase();
    return lower.startsWith('sms:') || lower.startsWith('smsto:');
  }

  @override
  ScanParseResult parse(ScanCandidate candidate) {
    final value = candidate.rawValue.trim();
    final lower = value.toLowerCase();
    final prefixLength = lower.startsWith('smsto:')
        ? 'smsto:'.length
        : 'sms:'.length;
    final remainder = value.substring(prefixLength);

    String recipientPart;
    String? body;
    final queryIndex = remainder.indexOf('?');
    if (queryIndex != -1) {
      recipientPart = remainder.substring(0, queryIndex);
      final params = Uri.splitQueryString(remainder.substring(queryIndex + 1));
      body = params['body'];
    } else {
      final colonIndex = remainder.indexOf(':');
      if (colonIndex != -1) {
        recipientPart = remainder.substring(0, colonIndex);
        body = remainder.substring(colonIndex + 1);
      } else {
        recipientPart = remainder;
      }
    }

    final recipient = normalizePhoneNumber(recipientPart);
    if (recipient.isEmpty) {
      return const ScanParseFailed(
        UnsupportedStructuredPayloadFailure('sms with no recipient'),
      );
    }

    return ScanParseSuccess(
      kind: ScanKind.sms,
      payload: SmsPayload(
        recipient: recipient,
        body: (body == null || body.isEmpty) ? null : body,
      ),
      title: recipient,
      normalizedValue: recipient,
    );
  }
}
